services:
  - type: web
    name: sistema-agricola
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn natureseek:natureseek"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0